fix: fix vote delegation
CarmineOptions/konoha pull request #100
Opened 2024-05-31 16:55 UTC by EjembiEmmanuel

@tensojka I've fixed the the issues with vote delegation. Please review to be sure I'm going in the right direction before I add the tests. Thank you!

2024-06-01 11:13 UTC, tensojka reviewed
Is the only thing you did uncomment the code? Does it work? Did you test it? Not sure what to review.

Sorry for not catching this earlier, please request a review from me (assigning me as a reviewer).

2024-06-01 12:05 UTC, EjembiEmmanuel commented
The code now compiles successfully, which was not the case initially. The initial issue was due to the absence of `withdraw_delegation` and `delegate_vote` declarations in the `IProposals` trait.

Additionally, there was an error in the code that retrieves the `gov_token_addr`. The incorrect line of code (line 400) was commented out:
`// let gov_token_addr = self.get_governance_token_address();`

This was corrected on line 401 with the following code:
`let gov_token_addr = IGovernanceDispatcher { contract_address: get_contract_address() }
.get_governance_token_address();`

At this point, I have not yet written tests for the code. I just wanted to get your feedback before proceeding with writing the tests.

2024-06-02 13:41 UTC, tensojka reviewed
Fine so far. There should be more quite a bit tests though

2024-06-02 13:41 UTC, tensojka commented on tests/proposals_tests.cairo
> +fn test_withdrae_delegation_with_incorrect_calldata() {
typo

2024-06-02 14:00 UTC, EjembiEmmanuel commented on tests/proposals_tests.cairo
> +fn test_withdrae_delegation_with_incorrect_calldata() {
Oh yea, thanks!

2024-06-02 21:53 UTC, tensojka requested changes
Still missing [] Delegate, vote and withdraw test

Otherwise LGTM!

2024-06-02 21:56 UTC, EjembiEmmanuel commented
> Still missing [] Delegate, vote and withdraw test
> 
> Otherwise LGTM!

Working on it!

2024-06-03 14:21 UTC, merged

2024-06-03 14:21 UTC, tensojka reviewed
LGTM, thanks!