Discussion with onchain data #76
CarmineOptions/konoha pull request #101
Opened 2024-06-01 11:38 UTC by manlikeHB

Closes #76 
- [ ] Implement discussion component with add and retrieve comment functions
- [ ] should depend on the Proposals component for fetching live proposals
- [ ] Update tests in tests/proposals.cairo

2024-06-01 11:42 UTC, manlikeHB commented
@tensojka This is what I have so far.

2024-06-01 12:11 UTC, tensojka requested changes
Looks okay so far, good luck with the time. It should be finished and tested by end of today so we can have tomorrow for reviews

2024-06-01 12:11 UTC, tensojka commented on src/discussion.cairo
> +        fn add_comment(ref self: ComponentState<TContractState>, prop_id: felt252, ipfs_hash: felt252) {
you do not depend on the Proposals component, see definition of Upgrades for how to depend on a component

2024-06-01 12:11 UTC, tensojka commented on src/discussion.cairo
> +            //TODO
Also check that the submitter is a CARM token holder and save their address to serve alongside the hash. I didn't realise this earlier, sorry for that.

2024-06-01 12:11 UTC, tensojka commented on src/discussion.cairo
> +        }
Can't you just `return` once finding the proposal in `get_live_proposals`?

2024-06-01 12:11 UTC, tensojka commented on src/lib.cairo
> +mod discussion;
sort alphabetically please

2024-06-01 17:02 UTC, tensojka commented on src/discussion.cairo
> +                panic!("CARM balance is Zero!");
As Konoha is generic, the message shouldn't directly reference CARM, "Govtoken balance is zero" would be better.

Use assert()

2024-06-02 15:52 UTC, manlikeHB commented
Hi @tensojka, my PR is ready for review.

2024-06-03 12:53 UTC, tensojka requested changes
Very good, only a few tidbits.

Where is the testnet deployment?

2024-06-03 12:53 UTC, tensojka commented on src/discussion.cairo
> +        ipfs_hash: felt252,
How will a IPFS hash fit into felt252? It will not. You must use a different data structure, possibly ByteArray.

2024-06-03 12:53 UTC, tensojka commented on src/discussion.cairo
> +        fn add_comment(ref self: ComponentState<TContractState>, prop_id: felt252, ipfs_hash: felt252) {
prop_id is being migrated to be u32, please use that

2024-06-03 12:53 UTC, tensojka commented on src/discussion.cairo
> +            let govtoken_addr = get_governance_token_address_self();
👍

2024-06-03 12:53 UTC, tensojka commented on src/discussion.cairo
> +        fn get_comment(self: @ComponentState<TContractState>, prop_id: felt252) -> Array<(ContractAddress, felt252)> {
Why are you returning an array of ContractAddress, felt252 and not `Comment`? (struct)

2024-06-03 12:53 UTC, tensojka commented on src/discussion.cairo
> +    impl Proposals: proposals_component::HasComponent<TContractState>,
Do you need to depend on Proposals here too? Isn't it enough to depend on it in the InternalTrait?

2024-06-03 12:53 UTC, tensojka commented on src/discussion.cairo
> +            //Get live proposals
Comments are to be used to clarify unclear parts of the code, this is superfluous

2024-06-03 12:53 UTC, tensojka commented on tests/proposals_tests.cairo
> +    prank, CheatSpan, stop_prank
unused import stop_prank

2024-06-03 12:53 UTC, tensojka commented on tests/proposals_tests.cairo
> +    let ipfs_hash = 1234567;
See, had you tested with a real ipfs hash, you would catch that it won't fit in felt252 ;)

2024-06-03 12:53 UTC, tensojka commented on src/discussion.cairo
> +        fn get_comment(self: @ComponentState<TContractState>, prop_id: felt252) -> Array<(ContractAddress, felt252)> {
Rename to get_comments

2024-06-04 14:41 UTC, tensojka reviewed
Good overall, I will fix these minor issues. I don't like that this was not tested on testnet and that the tests are very basic.

2024-06-04 14:41 UTC, tensojka commented on src/discussion.cairo
> +            }
I don't think this is needed as the break on line 84 will get triggered immediately

2024-06-04 14:41 UTC, tensojka commented on src/discussion.cairo
> +                // arr.append((com.user, com.ipfs_hash));
Remove commented out code, please

2024-06-04 14:41 UTC, tensojka commented on src/discussion.cairo
> +
This should be a bool

2024-06-08 11:20 UTC, tensojka approved these changes

2024-06-08 11:21 UTC, merged